### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by NathanJPhillips** [AvinZarlez/vscode-comment-snippets#1]
I'm going to have to look at the code to work out how to use this.

**Comment by AvinZarlez** [comment]
What kind of documentation were you hoping to find for a simple extension like this? A list of all the snippets it provides? I'm not sure if that is common for snippet extensions.

**Comment by NathanJPhillips** [comment]
After opening this issue I managed to find the video you created. That was the sort of level I needed, though text is better than video generally.

**Comment by Noitidart** [comment]
A gif showing how it works would be nice. I was looking for an extension that could do a block comment on selection within a line. Default vscode block comment, extends it to the beginning and end of lines of highlight.

**Comment by AvinZarlez** [comment]
@Noitidart Good feedback!

This seems like two requests:

1. An animated gif showing the snippets in action
2. A feature to create an in-line comment block

Though for the second request, that wouldn't be a "Snippet" as per VS Codes definition, and more like a feature of a comment improving extension. That said, I'm open to the idea of expanding the scope of this extension to something more general comment experience improving.

Would you, or anyone else reading this be interested in creating a PR with one of those two requests?

The first should be rather easy if you have the software, the second requires some coding but also should be fairly easy relatively to do.

**Comment by Noitidart** [comment]
Thanks sir, I honestly can't figure out how to use your extension, otherwise I would make the gif for you.

**Comment by AvinZarlez** [comment]
I demo it in this video: https://channel9.msdn.com/Events/ToolJam/2016/VSCode

Made this real quick while hosting a hackathon. It simply adds snippets.

Simply start typing "comment" and select one of the options to auto complete.

**Comment by Noitidart** [comment]
Ohhhh very cool thank you sir for sharing that!!
